title: Христина Кузьмина, клинический психолог
description: Клинический психолог Христина Кузьмина с опытом частной практики с 2017 года. Предлагаю психологические консультации онлайн.
url: "https://lisichko.net" # Укажите URL вашего сайта
baseurl: "" # Оставьте пустым, если сайт расположен в корневом каталоге
permalink: /:name/ # Настройка красивых URL без .html

# Настройки GitHub Pages
github:
  is_project_page: false # Установите false, если это пользовательская страница (например, username.github.io)

# Параметры для Jekyll (если вы используете Jekyll)
# Отключите создание ненужных файлов
exclude:
  - "README.md"
  - "LICENSE"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"

# Настройки для темы (если используете тему)
theme: jekyll-theme-cayman # Укажите название темы Jekyll, если используете

# Параметры для плагинов Jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
